# Generated by Django 3.2.5 on 2022-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('quan', models.IntegerField(default=0)),
                ('t_price', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('vol', models.IntegerField(default=100)),
                ('d_1price', models.IntegerField(default=0)),
                ('regdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('gubun', models.CharField(default='B', max_length=1)),
                ('price', models.IntegerField(default=0)),
                ('quan', models.IntegerField(default=0)),
                ('tquan', models.IntegerField(default=0, null=True)),
                ('buyer', models.CharField(max_length=50, null=True)),
                ('seller', models.CharField(max_length=50, null=True)),
                ('tradeyn', models.CharField(default='N', max_length=1)),
                ('time1', models.DateTimeField(auto_now=True)),
                ('time2', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('url', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=100)),
                ('user_pwd', models.TextField(max_length=100)),
                ('user_name', models.TextField(max_length=100)),
                ('user_acct', models.CharField(max_length=100)),
                ('user_amt', models.IntegerField(default=30000000)),
                ('user_regdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballance',
            constraint=models.UniqueConstraint(fields=('user_id', 'code'), name='unique ballance'),
        ),
    ]
